# Generated by Django 4.1.1 on 2022-10-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firRegistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('update_id', models.IntegerField(primary_key=True, serialize=False)),
                ('update_time', models.TimeField(max_length=20)),
                ('fir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firRegistration.firregistration')),
            ],
        ),
    ]
