# Generated by Django 4.1.1 on 2022-10-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirRegistration',
            fields=[
                ('fir_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fir_date', models.DateField(max_length=20)),
                ('fir_type', models.DateField(max_length=20)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.user_profile')),
            ],
        ),
    ]
