# Generated by Django 4.1.1 on 2022-10-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('emergency_contact_number', models.IntegerField(primary_key=True, serialize=False)),
                ('emergency_contact_type', models.CharField(max_length=20)),
                ('emergency_contact_place', models.CharField(max_length=20)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.police')),
            ],
        ),
    ]
