# Generated by Django 4.1.1 on 2022-10-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_report_type', models.CharField(max_length=20)),
                ('crime_report_place', models.CharField(max_length=20)),
                ('crime_report_name', models.CharField(max_length=20)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.user_profile')),
            ],
        ),
    ]
